import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { fetchJobs, fetchSheetMeta, resumeFileUrl, type JobRow } from '../api';

export default function Resumes() {
  const [jobs, setJobs] = useState<JobRow[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [tab, setTab] = useState('');
  const [metaTab, setMetaTab] = useState('');

  useEffect(() => {
    fetchSheetMeta()
      .then((m) => {
        setMetaTab(m.worksheet_tab);
        setTab((t) => t || m.worksheet_tab);
      })
      .catch((e) => setError(String(e)));
  }, []);

  useEffect(() => {
    if (!tab) return;
    setError(null);
    fetchJobs({
      tab,
      min_score: 0,
      limit: 200,
      has_resume: true,
    })
      .then((r) => setJobs(r.jobs))
      .catch((e) => setError(String(e)));
  }, [tab]);

  return (
    <>
      <h2>Tailored resumes</h2>
      <p className="lead">
        Rows with a non-empty <code>Resume Path</code> on the sheet (generated by the pipeline tailor phase
        or manual JD tooling). Files must live under the repo root to download.
      </p>

      <div className="filters">
        <label>
          Tab{' '}
          <input value={tab} onChange={(e) => setTab(e.target.value)} placeholder={metaTab || 'YYYY-MM-DD'} />
        </label>
      </div>

      {error && <div className="card err">{error}</div>}

      <table className="data">
        <thead>
          <tr>
            <th>Company</th>
            <th>Role</th>
            <th>Score</th>
            <th>Resume status</th>
            <th>Path</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {jobs.map((j) => (
            <tr key={j.row_index + j.resume_path}>
              <td>{j.company}</td>
              <td>{j.role_title}</td>
              <td className="score">{j.apply_score ?? '—'}</td>
              <td>{j.resume_status || '—'}</td>
              <td style={{ fontSize: '0.8rem', wordBreak: 'break-all' }}>{j.resume_path}</td>
              <td>
                <a href={resumeFileUrl(j.resume_path)} target="_blank" rel="noreferrer">
                  Open
                </a>{' '}
                · <Link to={`/job?url=${encodeURIComponent(j.job_link)}`}>Job</Link>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      {jobs.length === 0 && !error && <p className="lead">No tailored resume paths on this tab yet.</p>}
    </>
  );
}
